# Generated by Django 6.0.4 on 2026-04-10 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "barn_type",
                    models.CharField(
                        choices=[("POSTURA", "Postura"), ("CORTE", "Corte")],
                        max_length=10,
                    ),
                ),
                ("capacity", models.IntegerField()),
                ("level", models.IntegerField(default=1)),
                ("silo_capacity", models.IntegerField(default=5000)),
                ("silo_balance", models.FloatField(default=0.0)),
                (
                    "selected_feed_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_rented", models.BooleanField(default=False)),
                ("sanitary_void_days", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_count", models.IntegerField()),
                ("age_days", models.IntegerField(default=1)),
                ("mortality_count", models.IntegerField(default=0)),
                ("health", models.FloatField(default=100.0)),
                ("weight", models.FloatField(default=0.05)),
                (
                    "active_disease_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("active_disease_days", models.IntegerField(default=0)),
                (
                    "disease_treatment_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_integrated", models.BooleanField(default=False)),
                (
                    "barn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch",
                        to="core.barn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_color", models.CharField(default="#10b981", max_length=20)),
                ("money", models.FloatField(default=10000.0)),
                ("total_profit", models.FloatField(default=0.0)),
                ("total_expenses", models.FloatField(default=0.0)),
                ("current_month_revenue", models.FloatField(default=0.0)),
                ("has_feed_mill", models.BooleanField(default=False)),
                ("has_incubator", models.BooleanField(default=False)),
                ("has_slaughterhouse", models.BooleanField(default=False)),
                ("current_day", models.IntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="barn",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barns",
                to="core.player",
            ),
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eggs", models.IntegerField(default=0)),
                ("meat", models.FloatField(default=0.0)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=50)),
                ("quantity", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "item_id")},
            },
        ),
    ]
