# Generated by Django 6.0.4 on 2026-04-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="active_research_days_left",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="active_research_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="player",
            name="xp",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="PlayerResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("research_id", models.CharField(max_length=50)),
                ("level", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researches",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "research_id")},
            },
        ),
    ]
